In [1]:
from math import sin, cos, pi, trunc
import numpy as np
import cv2
from shapely.geometry import Polygon
from moviepy.editor import *

In [4]:
FILEPATH = "media/dreams_that_money_can_buy.mp4"
def get_subclip(filepath, t_start, t_end):
    t_start_secs = t_start[0] * 60 + t_start[1] 
    t_end_secs = t_end[0] * 60 + t_end[1] 
    clip = VideoFileClip(filepath)
    clip = clip.subclip(t_start_secs, t_end_secs)
    return clip

ts_min = 24
ts_sec = 0

te_min = 24
te_sec = 8
clip = get_subclip(FILEPATH, [ts_min, ts_sec], [te_min, te_sec])


In [6]:
clip.write_videofile('mannequinn.mp4')

Moviepy - Building video mannequinn.mp4.
MoviePy - Writing audio in mannequinnTEMP_MPY_wvf_snd.mp3


MoviePy - Done.
Moviepy - Writing video mannequinn.mp4



Moviepy - Done !
Moviepy - video ready mannequinn.mp4


In [8]:
# Function to extract frames 
def FrameCapture(path): 
  
    # Path to video file 
    vidObj = cv2.VideoCapture(path) 
  
    # Used as counter variable 
    count = 0
  
    # checks whether frames were extracted 
    success = 1
  
    while success: 
  
        # vidObj object calls read 
        # function extract frames 
        success, image = vidObj.read() 
        if image.shape[2] == 4:
            print("Image has an alpha channel") 
        else:
            print('none')

  
        # Saves the frames with frame-count 
        cv2.imwrite(f"media/mannequinn_frames/{count}.png", image) 
  
        count += 1

In [9]:
FILEPATH = "media/mannequinn.mp4"
FrameCapture(FILEPATH)

error: OpenCV(4.10.0) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:798: error: (-215:Assertion failed) !_img.empty() in function 'cv::imwrite'


In [ ]:
def get_perimeter_coords(img_file):
    image = cv2.imread(img_file, cv2.IMREAD_UNCHANGED)  
    image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    cv2.imshow('img', image_gray)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [11]:
count = 1
get_perimeter_coords(f"media/mannequinn_frames/{count}.png")

[[2 3 6 ... 5 5 3]
 [2 3 6 ... 5 5 3]
 [2 3 6 ... 5 5 3]
 ...
 [2 3 6 ... 5 4 3]
 [2 3 6 ... 4 3 3]
 [2 3 6 ... 4 3 3]]


: 